services:
  app:
    build: .
    container_name: portfolio_app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - database

  database:
    image: postgres:16-alpine
    container_name: portfolio_db
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"

  mailer:
    image: axllent/mailpit
    container_name: portfolio_mailer
    ports:
      - "1025:1025"
      - "8025:8025"